name: schedule-app

services:
  front:
    image: "schedule-front:latest"
    restart: unless-stopped
    build: ./front
    ports:
     - 4200:4200

  db:
    image: "schedule-db:latest"
    restart: unless-stopped
    build: ./db
    ports:
      - 3000:3000
